version: ~> 1.0

language: java
os: linux
dist: bionic

jdk:
  - openjdk8
  - openjdk11

deploy:
  - provider: script
    script: ./gradlew publishPlugins -Pgradle.publish.key="${GRADLE_PUBLISH_KEY}" -Pgradle.publish.secret="${GRADLE_PUBLISH_SECRET}"
    skip_cleanup: true
    on:
      branch: master
      repo: Heapy/heapy-properties-gradle-plugin
      jdk: openjdk8

