version: ~> 1.0

language: java
os: linux
dist: bionic

jdk:
  - openjdk8
  - openjdk11

script:
  - ./gradlew assemble
  - ./gradlew check
  - cd "${TRAVIS_BUILD_DIR}/manual-test/" && ./gradlew validate
  - cd "${TRAVIS_BUILD_DIR}/manual-test-config/" && ./gradlew validate
  - cd "${TRAVIS_BUILD_DIR}"

deploy:
  - provider: script
    script: ./publish.sh
    skip_cleanup: true
    on:
      branch: master
      repo: Heapy/heapy-properties-gradle-plugin
      jdk: openjdk8

